# Generated by Django 5.0.4 on 2024-06-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='BooksModel',
        ),
    ]
