# Generated by Django 5.0.4 on 2024-06-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likesmodel',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
    ]
