# Generated by Django 5.0.4 on 2024-06-26 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='tag_user',
            field=models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='posts.tagsmodel'),
        ),
    ]
