# Generated by Django 5.0.4 on 2024-07-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['created_at'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
