# Generated by Django 5.0.4 on 2024-06-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=254)),
                ('pages', models.IntegerField()),
                ('in_stock', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('isbn', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
