# Generated by Django 5.0.4 on 2024-06-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationmodel',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
