# Generated by Django 5.0.4 on 2024-07-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storymodel',
            options={'ordering': ('-expire_time',), 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.RenameField(
            model_name='storymodel',
            old_name='expiry_time',
            new_name='expire_time',
        ),
    ]
