# Generated by Django 5.0.4 on 2024-07-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='avatar',
        ),
    ]
